services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=fly
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql